#!/bin/bash

set -e

# tell phone to start usb tether
adb shell su -c service call connectivity 33 i32 1
# set ttl on outgoing usb0 packets
iptables -t mangle -I POSTROUTING -m physdev --physdev-out usb0 -j TTL --ttl-set 65
